#!/usr/bin/env /bin/bash

tag=$(curl --silent "https://api.github.com/repos/babashka/babashka-sql-pods/tags" | jq -r '.[0].name')
version=${tag:1}
linux="pod-babashka-postgresql-$version-linux-amd64.zip"
macos="pod-babashka-postgresql-$version-macos-amd64.zip"
linux_sha=$(sha256sum "$linux" | cut -f 1 -d " ")
macos_sha=$(sha256sum "$macos" | cut -f 1 -d " ")

sed -e "s/\${i}/1/" -e "s/\${VERSION}/$version/g" \
    -e "s/\${LINUX_SHA}/$linux_sha/g" \
    -e "s/\${MACOS_SHA}/$macos_sha/g" \
    pod-babashka-postgresql.template > pod-babashka-postgresql.rb
