#!/usr/bin/env /bin/bash

tag=$(curl --silent "https://api.github.com/repos/borkdude/carve/tags" | jq -r '.[0].name')
version=${tag:1}
linux="carve-$version-linux-amd64.zip"
macos="carve-$version-macos-amd64.zip"
linux_sha=$(sha256sum "$linux" | cut -f 1 -d " ")
macos_sha=$(sha256sum "$macos" | cut -f 1 -d " ")

sed -e "s/\${i}/1/" -e "s/\${VERSION}/$version/g" \
    -e "s/\${LINUX_SHA}/$linux_sha/g" \
    -e "s/\${MACOS_SHA}/$macos_sha/g" \
    carve.template > carve.rb
