#!/usr/bin/env /bin/bash

tag=$(curl --silent "https://api.github.com/repos/clj-kondo/clj-kondo/tags" | jq -r '.[0].name')
version=${tag:1}

curl -sLO "https://github.com/clj-kondo/clj-kondo/releases/download/v$version/clj-kondo-$version-linux-amd64.zip"
curl -sLO "https://github.com/clj-kondo/clj-kondo/releases/download/v$version/clj-kondo-$version-macos-amd64.zip"
curl -sLO "https://github.com/clj-kondo/clj-kondo/releases/download/v$version/clj-kondo-$version-macos-aarch64.zip"

linux="clj-kondo-$version-linux-amd64.zip"
macos_arm="clj-kondo-$version-macos-aarch64.zip"
macos_amd="clj-kondo-$version-macos-amd64.zip"
linux_sha=$(sha256sum "$linux" | cut -f 1 -d " ")
macos_amd_sha=$(sha256sum "$macos_amd" | cut -f 1 -d " ")
macos_arm_sha=$(sha256sum "$macos_arm" | cut -f 1 -d " ")

sed -e "s/\${i}/1/" -e "s/\${VERSION}/$version/g" \
    -e "s/\${LINUX_SHA}/$linux_sha/g" \
    -e "s/\${MACOS_ARM_SHA}/$macos_arm_sha/g" \
    -e "s/\${MACOS_AMD_SHA}/$macos_amd_sha/g" \
    clj-kondo.template > clj-kondo.rb
