#!/usr/bin/env /bin/bash

tag=$(curl --silent "https://api.github.com/repos/borkdude/clj-kondo/tags" | jq -r '.[0].name')
version=${tag:1}
linux="clj-kondo-$version-linux-amd64.tar.gz"
macos="clj-kondo-$version-macos-amd64.tar.gz"
linux_sha=$(sha256sum "$linux" | cut -f 1 -d " ")
macos_sha=$(sha256sum "$macos" | cut -f 1 -d " ")

sed -e "s/\${i}/1/" -e "s/\${VERSION}/$version/g" \
    -e "s/\${LINUX_SHA}/$linux_sha/g" \
    -e "s/\${MACOS_SHA}/$macos_sha/g" \
    clj-kondo.template > clj-kondo.rb
